## Logistic Regression Model - (final)

In [1]:
# Initial imports.
import pandas as pd
import numpy as np
from path import Path
from pathlib import Path
from collections import Counter
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import warnings
warnings.filterwarnings('ignore')

# import dependencies for sql connection
import pandas as pd
from sqlalchemy import create_engine
import psycopg2
import config
from path import Path
from config import db_password

In [2]:
## Connection Setup
db_connect = f"postgresql://postgres:{db_password}@localhost:5432/capstone_db"

# Create the connection
cnx = create_engine(db_connect)

In [3]:
# query from SQL
stroke_df = pd.read_sql('''SELECT * FROM stroke3_table''', con=cnx)

In [4]:
stroke_df.head()

index  age  gender ever_married   smoking_status  hypertension  \
0      0    3    Male           No          unknown             0   
1      1   58    Male          Yes     never smoked             1   
2      2    8  Female           No          unknown             0   
3      3   70  Female          Yes  formerly smoked             0   
4      4   14    Male           No          unknown             0   

   heart_disease  stroke  
0              0       0  
1              0       0  
2              0       0  
3              0       0  
4              0       0

In [5]:
# drop index
stroke_df = stroke_df.drop("index", axis=1)

In [6]:
stroke_df.head()

age  gender ever_married   smoking_status  hypertension  heart_disease  \
0    3    Male           No          unknown             0              0   
1   58    Male          Yes     never smoked             1              0   
2    8  Female           No          unknown             0              0   
3   70  Female          Yes  formerly smoked             0              0   
4   14    Male           No          unknown             0              0   

   stroke  
0       0  
1       0  
2       0  
3       0  
4       0

## Preprocess data

In [7]:
# Use scikit-learn to encode data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

stroke_df['gender'] = le.fit_transform(stroke_df['gender'])
stroke_df['ever_married'] = le.fit_transform(stroke_df['ever_married'])
stroke_df['smoking_status'] = le.fit_transform(stroke_df['smoking_status'])
stroke_df.head()

age  gender  ever_married  smoking_status  hypertension  heart_disease  \
0    3       1             0               3             0              0   
1   58       1             1               1             1              0   
2    8       0             0               3             0              0   
3   70       0             1               0             0              0   
4   14       1             0               3             0              0   

   stroke  
0       0  
1       0  
2       0  
3       0  
4       0

## Scale & Normalize

In [8]:
# load scaler
data_scaler = StandardScaler()

In [9]:
# train the scaler and transform the data
stroke_data_scaled = data_scaler.fit_transform(stroke_df)

In [10]:
# preview scaled data
stroke_data_scaled[:5]

array([[-1.73913268,  1.20108119, -1.34420288,  1.28640708, -0.32129564,
        -0.22334159, -0.13554685],
       [ 0.70066001,  1.20108119,  0.74393532, -0.53968634,  3.11239826,
        -0.22334159, -0.13554685],
       [-1.51733334, -0.83084068, -1.34420288,  1.28640708, -0.32129564,
        -0.22334159, -0.13554685],
       [ 1.23297842, -0.83084068,  0.74393532, -1.45273305, -0.32129564,
        -0.22334159, -0.13554685],
       [-1.25117414,  1.20108119, -1.34420288,  1.28640708, -0.32129564,
        -0.22334159, -0.13554685]])

In [11]:
# verify the mean
print(np.mean(stroke_data_scaled[:,0]))
print(np.std(stroke_data_scaled[:,0]))

-1.0314330035227261e-16
0.9999999999999999


## Split data into Train and Test

In [12]:
# Create our features
X = stroke_df[['age', 'gender', 'ever_married', 'hypertension', 'heart_disease', 'smoking_status']]

# Create our target
y = stroke_df["stroke"]

In [13]:
# Check the balance of our target values
y.value_counts()

0    42617
1      783
Name: stroke, dtype: int64

In [14]:
# Split into training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [15]:
X_train.shape

(32550, 6)

In [16]:
X_test.shape

(10850, 6)

## Oversample the Data

In [17]:
# Resample the training data with the RandomOversampler
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=42)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

## Run Logistic Regression

In [18]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state=42)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=42)

In [19]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[7788, 2854],
       [  44,  164]])

In [20]:
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, y_pred)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

Predicted 0  Predicted 1
Actual 0         7788         2854
Actual 1           44          164

In [21]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)

0.760139433015772

In [22]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.99      0.73      0.79      0.84      0.76      0.57     10642
          1       0.05      0.79      0.73      0.10      0.76      0.58       208

avg / total       0.98      0.73      0.79      0.83      0.76      0.57     10850



In [23]:
model.predict([[0,0,0,0,0,0]])

array([0])

In [24]:
stroke_df.head()

age  gender  ever_married  smoking_status  hypertension  heart_disease  \
0    3       1             0               3             0              0   
1   58       1             1               1             1              0   
2    8       0             0               3             0              0   
3   70       0             1               0             0              0   
4   14       1             0               3             0              0   

   stroke  
0       0  
1       0  
2       0  
3       0  
4       0

In [25]:
print(f"Training Data Score: {model.score(X_resampled, y_resampled)}")
print(f"Testing Data Score: {model.score(X_test, y_test)}")

Training Data Score: 0.7678342455043002
Testing Data Score: 0.7329032258064516


In [53]:
stroke_df[['age', 'gender', 'ever_Married', 'smoking_Status', 'hypertension', 'heart_disease', 'stroke']].to_csv('db.csv')